# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminID', models.CharField(max_length=11)),
                ('adminEmail', models.CharField(max_length=80)),
                ('adminName', models.CharField(max_length=50)),
                ('adminPassword', models.CharField(max_length=30)),
                ('adminImageUrl', models.CharField(max_length=500)),
                ('adminBroadmoor', models.CharField(max_length=2)),
                ('adminLogoImageUrl', models.CharField(max_length=50)),
                ('adminCompany', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Announce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('an_id', models.CharField(max_length=11)),
                ('adminID', models.CharField(max_length=11)),
                ('an_image', models.CharField(max_length=500)),
                ('an_title', models.CharField(max_length=300)),
                ('an_audience', models.CharField(max_length=300)),
                ('an_subject', models.CharField(max_length=300)),
                ('an_description', models.CharField(max_length=4000)),
                ('an_callofaction', models.CharField(max_length=300)),
                ('an_owneremail', models.CharField(max_length=80)),
                ('an_viewnum', models.CharField(max_length=11)),
                ('an_responsenum', models.CharField(max_length=11)),
                ('an_postdate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AnnounceView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_id', models.CharField(max_length=11)),
                ('an_id', models.CharField(max_length=11)),
                ('em_id', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='BroadmoorProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bm_proid', models.CharField(max_length=11)),
                ('adminID', models.CharField(max_length=11)),
                ('bm_proImageUrl', models.CharField(max_length=500)),
                ('bm_proName', models.CharField(max_length=300)),
                ('bm_proInventoryNum', models.CharField(max_length=11)),
                ('bm_proCategory', models.CharField(max_length=100)),
                ('bm_proAdditional', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='BroadmoorProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bm_detailID', models.CharField(max_length=11)),
                ('bm_proid', models.CharField(max_length=11)),
                ('bm_proSize', models.CharField(max_length=100)),
                ('bm_proQuantity', models.CharField(max_length=11)),
                ('bm_proPrice', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_id', models.CharField(max_length=11)),
                ('adminID', models.CharField(max_length=11)),
                ('em_image', models.CharField(max_length=500)),
                ('em_name', models.CharField(max_length=80)),
                ('em_gender', models.CharField(max_length=20)),
                ('em_email', models.CharField(max_length=80)),
                ('em_password', models.CharField(max_length=30)),
                ('em_millennial', models.CharField(max_length=20)),
                ('em_givenbuck', models.CharField(max_length=11)),
                ('em_usedbuck', models.CharField(max_length=11)),
                ('em_interaction', models.CharField(max_length=11)),
                ('em_status', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=11)),
                ('adminID', models.CharField(max_length=11)),
                ('job_name', models.CharField(max_length=200)),
                ('job_req', models.CharField(max_length=11)),
                ('job_department', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=100)),
                ('job_description', models.CharField(max_length=4000)),
                ('job_postdate', models.CharField(max_length=30)),
                ('job_empty', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemid', models.CharField(max_length=11)),
                ('proid', models.CharField(max_length=11)),
                ('itemPictureUrl', models.CharField(max_length=500)),
                ('itemBrand', models.CharField(max_length=80)),
                ('itemProduct', models.CharField(max_length=80)),
                ('itemName', models.CharField(max_length=200)),
                ('itemSize', models.CharField(max_length=200)),
                ('itemPrice', models.CharField(max_length=10)),
                ('itemDescription', models.CharField(max_length=4000)),
                ('itemInventoryNum', models.CharField(max_length=11)),
                ('itemSaleStatus', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proid', models.CharField(max_length=11)),
                ('adminID', models.CharField(max_length=11)),
                ('proProfileImageUrl', models.CharField(max_length=500)),
                ('proFirstName', models.CharField(max_length=50)),
                ('proLastName', models.CharField(max_length=50)),
                ('proEmail', models.CharField(max_length=80)),
                ('proPassword', models.CharField(max_length=30)),
                ('proCity', models.CharField(max_length=50)),
                ('proAddress', models.CharField(max_length=50)),
                ('proCompany', models.CharField(max_length=50)),
                ('proToken', models.CharField(max_length=500)),
                ('proServicePercent', models.CharField(max_length=8)),
                ('proSalary', models.CharField(max_length=20)),
                ('proProductSalePercent', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceid', models.CharField(max_length=11)),
                ('proid', models.CharField(max_length=11)),
                ('proServicePictureUrl', models.CharField(max_length=500)),
                ('proBeautyCategory', models.CharField(max_length=100)),
                ('proBeautySubCategory', models.CharField(max_length=100)),
                ('proServicePrice', models.CharField(max_length=8)),
                ('proServiceDescription', models.CharField(max_length=4000)),
            ],
        ),
    ]
